### ISSUE TITLE
`atQuery` option is renamed `mediaQuery` in v0.5.0

### ISSUE THREAD

**Issue by meduzen** [hemengke1997/postcss-pxtorem#1]
In 16b66b0, the `mediaQuery` option [has been changed to `atQuery`](https://github.com/hemengke1997/postcss-pxtorem/blame/16b66b03b66d1698c17664194b4df39dd7d25a21/src/index.ts#L24), but it isn’t documented, so I guess a choice should be made and documented.

I propose to go for `atRule`, because it’s the [official CSS terminology](https://drafts.csswg.org/css-syntax-3/#at-rule) (and it’s also used by PostCSS).

Also, I’d consider accepting an array (in addition to boolean) for this one, in case someone wants to convert `@media` and `@container` but leave `@supports` untouched for some reasons.

What do you think?

**Comment by hemengke1997** [comment]
Sounds good to me. I'll deal with it later
Thanks for your advice :)

**Comment by hemengke1997** [comment]
fixed in `0.0.6`
