### ISSUE TITLE
Changelog not updated

### ISSUE THREAD

**Issue by meduzen** [hemengke1997/postcss-pxtorem#3]
Hi! As I’m watching the repository, I noticed the [releases](https://github.com/hemengke1997/postcss-pxtorem/releases) always refer to the changelog for the changes, but the changelog is not up-to-date.

(I don’t know if this repo uses an automatic process for this or not, sorry if this issue feels off for some reason.)

Thanks again for your work on this package, it’s a very important CSS area. 🙏

**Comment by hemengke1997** [comment]
oops, I didn't notice this.

I have not made `release` workflow yet. TBH I forgot this.
I'll fix it soon. Thank you!!
